name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - run: mise run update
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - id: pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: fix/update-formulae
          commit-message: "fix: update formulae"
          title: "fix: update formulae"
          body: |
            Update the Homebrew formulae to the latest upstream releases.
      - if: ${{ steps.pr.outputs.pull-request-number }}
        run: gh pr merge '${{ steps.pr.outputs.pull-request-number }}' --auto --merge
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
